#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dbus
Version  : 1.9.10
Release  : 31
URL      : http://dbus.freedesktop.org/releases/dbus/dbus-1.9.10.tar.gz
Source0  : http://dbus.freedesktop.org/releases/dbus/dbus-1.9.10.tar.gz
Summary  : Free desktop message bus
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 GPL-2.0+
Requires: dbus-bin
Requires: dbus-config
Requires: dbus-lib
Requires: dbus-data
Requires: dbus-doc
BuildRequires : cmake
BuildRequires : expat-dev
BuildRequires : gettext
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(valgrind)
BuildRequires : pkgconfig(x11)
BuildRequires : xmlto
Patch1: 0001-Add-support-for-ignore_missing-attributed-in-include.patch
Patch2: 0002-Stateless.patch
Patch3: malloc_trim.patch
Patch4: fdpass-test-reduce-number-of-fds.patch
Patch5: memory.patch

%description
Sections in this file describe:
- introduction and overview
- low-level vs. high-level API
- version numbers
- options to the configure script
- ABI stability policy

%package bin
Summary: bin components for the dbus package.
Group: Binaries
Requires: dbus-data
Requires: dbus-config

%description bin
bin components for the dbus package.


%package config
Summary: config components for the dbus package.
Group: Default

%description config
config components for the dbus package.


%package data
Summary: data components for the dbus package.
Group: Data

%description data
data components for the dbus package.


%package dev
Summary: dev components for the dbus package.
Group: Development
Requires: dbus-lib
Requires: dbus-bin
Requires: dbus-data
Provides: dbus-devel

%description dev
dev components for the dbus package.


%package doc
Summary: doc components for the dbus package.
Group: Documentation

%description doc
doc components for the dbus package.


%package extras
Summary: extras components for the dbus package.
Group: Default

%description extras
extras components for the dbus package.


%package lib
Summary: lib components for the dbus package.
Group: Libraries
Requires: dbus-data
Requires: dbus-config

%description lib
lib components for the dbus package.


%prep
%setup -q -n dbus-1.9.10
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1

%build
%configure --disable-static --sysconfdir=/usr/share \
--with-systemdunitdir=/usr/lib/systemd/system \
--disable-doxygen-docs \
--disable-xml-docs
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/dbus-launch
%exclude /usr/libexec/dbus-daemon-launch-helper
/usr/bin/dbus-cleanup-sockets
/usr/bin/dbus-daemon
/usr/bin/dbus-monitor
/usr/bin/dbus-run-session
/usr/bin/dbus-send
/usr/bin/dbus-test-tool
/usr/bin/dbus-uuidgen

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/dbus.service
/usr/lib/systemd/system/dbus.socket
/usr/lib/systemd/system/dbus.target.wants/dbus.socket
/usr/lib/systemd/system/multi-user.target.wants/dbus.service
/usr/lib/systemd/system/sockets.target.wants/dbus.socket

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/session.conf
/usr/share/dbus-1/system.conf

%files dev
%defattr(-,root,root,-)
/usr/include/dbus-1.0/dbus/dbus-address.h
/usr/include/dbus-1.0/dbus/dbus-bus.h
/usr/include/dbus-1.0/dbus/dbus-connection.h
/usr/include/dbus-1.0/dbus/dbus-errors.h
/usr/include/dbus-1.0/dbus/dbus-macros.h
/usr/include/dbus-1.0/dbus/dbus-memory.h
/usr/include/dbus-1.0/dbus/dbus-message.h
/usr/include/dbus-1.0/dbus/dbus-misc.h
/usr/include/dbus-1.0/dbus/dbus-pending-call.h
/usr/include/dbus-1.0/dbus/dbus-protocol.h
/usr/include/dbus-1.0/dbus/dbus-server.h
/usr/include/dbus-1.0/dbus/dbus-shared.h
/usr/include/dbus-1.0/dbus/dbus-signature.h
/usr/include/dbus-1.0/dbus/dbus-syntax.h
/usr/include/dbus-1.0/dbus/dbus-threads.h
/usr/include/dbus-1.0/dbus/dbus-types.h
/usr/include/dbus-1.0/dbus/dbus.h
/usr/lib64/*.so
/usr/lib64/dbus-1.0/include/dbus/dbus-arch-deps.h
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/dbus/*

%files extras
%defattr(-,root,root,-)
/usr/bin/dbus-launch

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
